### ISSUE TITLE
Docker images aren't available in Docker-hub

### ISSUE THREAD

**Issue by gagipro** [s8sg/faas-flow-tower#6]
Hi,

list-flow-functions
dot-generator
faas-flow-dashboard

images aren't available it seems? or perhaps it's only me and proxy issue

**Comment by s8sg** [comment]
I have bumped the version of the images into
```
s8sg/dot-generator:1.0.0
s8sg/list-flow-functions:1.0.0
s8sg/faas-flow-gateway:1.0.0
```
and pushed it to docker-hub

**Comment by gagipro** [comment]
ok thanks, tried to build.

anyway images seems to be ok, except for some probe issue on the gateway

**Comment by s8sg** [comment]
Dashboard doesn’t yet have the health check. There’s already an open issue for it #3
